mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import Home


urlpatterns = [
    url(r'^$', Home, name = 'home'),
    #url(r'^grappelli/', include('grappelli.urls')),
    url(r'^polls/', include ('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
    url (r'^$', views.IndexView.as_view(), name = 'index'),
    url (r'^(?P<question_id>[0-9]+)/$', views.details, name='details'),
    url (r'^(?P<question_id>[0-9]+)/results/$', views.result, name='results'),
    url (r'^(?P<question_id>[0-9]+)/votes/$', views.vote, name='votes'),

]

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

polls/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
import datetime
from django.utils import timezone

# Create your models here.

class Question (models.Model):
    question_text = models.CharField (max_length = 200, unique=True)
    pub_date = models.DateTimeField ('Date Published')
    def __str__(self):
        return self.question_text
    def was_published_recently (self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Was published recently ?'


class Choice (models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE) #HAHAHA
    choice_text = models.CharField (max_length = 200)
    votes = models.IntegerField (default = 0)
    def __str__(self):
        return self.choice_text

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
# Create your views here.

def Home (request):
    return HttpResponseRedirect('polls')

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question, Choice
from django.template import loader
from django.urls import reverse
from django.views import generic

# Create your views here.


def index (request):
    req= request
    lastest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = ', '.join([q.question_text for q in lastest_question_list])
    template = loader.get_template('polls/index.html')
    context = {
        'lastest_question_list': lastest_question_list,
        'req': req,
    }
    return render (request, 'polls/index.html', context)

def details (request, question_id):
    try:
        question = get_object_or_404(Question, pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render (request, 'polls/detail.html', {'question': question})

def result (request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    return render (request, 'polls/results.html', {'question': question})

class IndexView (generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'lastest_question_list'

    def queryset (self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView (generic.DetailView):
    model = Question
    template_name = 'polls/details.html'

class ResultView (generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote (request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get (pk = request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render (request, 'polls/details.html', {
            'question': question,
            'error_message': "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args = (question.id,)))

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:votes' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />


{% if lastest_question_list %}
    <ul>
    {% for question in lastest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote {{choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:details' question.id %}"> Wanna vote again ?</a>